server:
  port: 8080
  servlet:
    context-path: /pgsqldemo

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:postgresql://172.17.172.135:5432/testdb
    username: pguser
    password: passw0d
    druid:
      #初始化连接大小
      initial-size: 8
      #最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 10
      #查询超时时间
      query-timeout: 6000
      #事务查询超时时间
      transaction-query-timeout: 6000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
